name: freelance
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_reorderable_grid_view: ^4.0.0
  hexcolor: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: montserratfamily
      fonts:
        - asset: assets/fonts/static/Montserrat-Black.ttf
        - asset: assets/fonts/static/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/static/Montserrat-Bold.ttf
        - asset: assets/fonts/static/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/static/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/static/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/static/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/static/Montserrat-Light.ttf
        - asset: assets/fonts/static/Montserrat-Medium.ttf
        - asset: assets/fonts/static/Montserrat-Regular.ttf
        - asset: assets/fonts/static/Montserrat-SemiBold.ttf
        - asset: assets/fonts/static/Montserrat-Thin.ttf
